name: runbuilder
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wredundant-constraints

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - unordered-containers ^>= 0.2
  - aeson ^>= 2.0

library:
  source-dirs: src

executables:
  runbuilder:
    main: app/Main.hs
    dependencies:
      - bytestring ^>= 0.10
      - unix ^>= 2.7
      - filepath ^>= 1.4
      - directory ^>= 1.3
      - process ^>= 1.6
      - runbuilder
