name: hsnix-nixpkgs
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

extra-source-files:
  - src/HsNixPkgs/StdEnv/Linux/BootstrapTools/unpack-bootstrap-tools-musl.sh
  - src/HsNixPkgs/StdEnv/Linux/BootstrapTools/unpack-bootstrap-tools.sh

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - StandaloneDeriving

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - data-default ^>= 0.7
  - hsnix-core

library:
  source-dirs: src
  other-modules:
    - HsNixPkgs.HSScript.Internal.BuildMod
    - HsNixPkgs.HSScript.Internal.BuildMod.TH
    - HsNixPkgs.HSScript.Internal.BuildMod.Types
  dependencies:
    - template-haskell ^>= 2.17
    - mtl ^>= 2.2
    - containers ^>= 0.6
    - hashable ^>= 1.3
    - unordered-containers ^>= 0.2
    - filepath ^>= 1.4
    - directory ^>= 1.3
    - shell-gen
