name: hsnixpkgs-builder
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

flags:
  with-source:
    description: Wether embed source dist.
    default: true
    manual: true

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - bytestring ^>= 0.10
  - unix ^>= 2.7
  - filepath ^>= 1.4
  - directory ^>= 1.3
  - process ^>= 1.6

library:
  source-dirs: src
  dependencies:
    - template-haskell ^>= 2.17
  when:
    - condition: flag (with-source)
      source-dirs: src-source
      exposed-modules:
        - HsNixPkgs.Builders.Sources
      dependencies:
        - embed-sdist
