name: embed-sdist
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - template-haskell ^>= 2.17
  - Cabal ^>= 3.4
  - filepath ^>= 1.4
  - directory ^>= 1.3
  - hsnix-core

library:
  source-dirs: src
