module HsNixPkgs.BuildSupport.SetupHooks.PruneLibtoolFiles (pruneLibtoolFiles) where

import HsNixPkgs.ExtendDrv
import HsNixPkgs.Shell
import HsNixPkgs.Shell.Util

pruneLibtoolFiles :: MonadDeriv m => Script m (ScriptTerm m -> Script m ())
pruneLibtoolFiles =
  pure
    ( \d ->
        findCmdExec
          (quote d)
          ["-type", "f", "-name", quote "*la"]
          ( \it ->
              [ ["grep", "-q", quote "'^# Generated by .*libtool'", it],
                ["grep", "-q", quote "^old_library=''", it],
                ["sed", "-i", it, "-e", quote "/^dependency_libs='[^']/ c dependency_libs='' #pruned"]
              ]
          )
    )